### ISSUE TITLE
NCHAN_URI環境変数のプロトコルはws://ではないか

### ISSUE THREAD

**Issue by masan4444** [weseek/growi-docs#313]
## 箇所
https://github.com/weseek/growi-docs/blob/fb9ab941f8cfc900120fc1f78450d5f854809eb4/docs/ja/admin-guide/admin-cookbook/loadbalance.md?plain=1#L9-L16

## 指摘
```
NCHAN_URI=http://nchan
```
ではなく
```
NCHAN_URI=ws://nchan
```
ではないか

## 理由
- ```NCHAN_URI=http://nchan```と設定した場合、（複数のGrowi動作時に必要な）設定が同期しない

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04.1 LTS|
|GROWI     |5.1.0|
|node.js   |16.16.0|
|npm       |8.11.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|部分的にyes（nchan検証用にカスタマイズ）|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04.1 LTS|
|browser   |Google Chrome 107.0.5304.110（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. docker-compose.yamlをnchan検証用に修正
- nchanコンテナを追加
- `app`の環境変数に`NCHAN_URI=http://nchan`, `S2SMSG_PUBSUB_SERVER_TYPE=nchan`を追加
- `app`をもとに、nchan検証用として`app_1`（ポート3001でListen）, `app_2`（ポート3002でListen）を立ち上げるように修正
```yml
version: '3'

services:
  app_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:3001:3000    # localhost only by default
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
      - nchan:nchan
    depends_on:
      - mongo
      - elasticsearch
      - nchan
    environment:
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - NCHAN_URI=http://nchan
      - S2SMSG_PUBSUB_SERVER_TYPE=nchan
      - PASSWORD_SEED=changeme
      - FILE_UPLOAD=mongodb   # activate this line if you use MongoDB GridFS rather than AWS
      # - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
      # - MATHJAX=1             # activate this line if you want to use MathJax
      # - PLANTUML_URI=http://  # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
      # - HACKMD_URI=http://    # activate this line and specify HackMD server URI which can be accessed from GROWI client browsers
      # - HACKMD_URI_FOR_SERVER=http://hackmd:3000  # activate this line and specify HackMD server URI which can be accessed from this server container
      # - FORCE_WIKI_MODE='public'    # activate this line to force wiki public mode
      # - FORCE_WIKI_MODE='private'   # activate this line to force wiki private mode

    entrypoint: "dockerize
                  -wait tcp://mongo:27017
                  -wait tcp://elasticsearch:9200
                  -wait tcp://nchan:80
                  -timeout 60s
                  /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]

    restart: unless-stopped
    volumes:
      - app_data:/data

  app_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:3002:3000    # localhost only by default
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
      - nchan:nchan
    depends_on:
      - mongo
      - elasticsearch
      - nchan
    environment:
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - NCHAN_URI=http://nchan
      - S2SMSG_PUBSUB_SERVER_TYPE=nchan
      - PASSWORD_SEED=changeme
      - FILE_UPLOAD=mongodb   # activate this line if you use MongoDB GridFS rather than AWS
      # - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
      # - MATHJAX=1             # activate this line if you want to use MathJax
      # - PLANTUML_URI=http://  # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
      # - HACKMD_URI=http://    # activate this line and specify HackMD server URI which can be accessed from GROWI client browsers
      # - HACKMD_URI_FOR_SERVER=http://hackmd:3000  # activate this line and specify HackMD server URI which can be accessed from this server container
      # - FORCE_WIKI_MODE='public'    # activate this line to force wiki public mode
      # - FORCE_WIKI_MODE='private'   # activate this line to force wiki private mode

    entrypoint: "dockerize
                  -wait tcp://mongo:27017
                  -wait tcp://elasticsearch:9200
                  -wait tcp://nchan:80
                  -timeout 60s
                  /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]

    restart: unless-stopped
    volumes:
      - app_data:/data

  nchan:
    image: weseek/nginx-nchan:latest
    ports:
      - 8080:80

  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: ./Dockerfile
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  app_data:
  mongo_configdb:
  mongo_db:
  es_data:
```
2. docker-compose起動
  ```bash
  docker-compose up
  ```
3. localhost:3001（`app_1`）にブラウザでアクセスし、ユーザー作成を済ましたあと、アプリ設定画面から設定（サイト名など）を変更する
4. localhost:3002（`app_2`）にアクセスし、アプリ設定画面から設定を確認する 

What happens? (症状)
---------------------

- localhost:3002（`app_2`）の設定画面上で、localhost:3001（`app_1`）で行った変更が反映されていない
#### docker-compose起動時
```
app_1_1          | {"name":"growi","hostname":"e6d9cd7f0d4b","pid":17,"level":50,"msg":"Unhandled Rejection: Promise: Promise {\n  <rejected> SyntaxError: The URL's protocol must be one of \"ws:\", \"wss:\", or \"ws+unix:\"\n      at initAsClient (/opt/growi/node_modules/ws/lib/websocket.js:688:17)\n      at new WebSocket (/opt/growi/node_modules/ws/lib/websocket.js:84:7)\n      at /opt/growi/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:519:19\n      at runNextTicks (node:internal/process/task_queues:61:5)\n      at processTimers (node:internal/timers:499:9)\n} Reason: SyntaxError: The URL's protocol must be one of \"ws:\", \"wss:\", or \"ws+unix:\"\n    at initAsClient (/opt/growi/node_modules/ws/lib/websocket.js:688:17)\n    at new WebSocket (/opt/growi/node_modules/ws/lib/websocket.js:84:7)\n    at /opt/growi/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:519:19\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at processTimers (node:internal/timers:499:9)","time":"2022-11-13T13:22:27.497Z","v":0}
```
#### `app_2`で設定画面を表示したとき
```
app_2_1          | {"name":"growi:service:s2s-messaging:nchan","hostname":"addf8f957f30","pid":19,"level":30,"msg":"The connection to config pubsub server is offline. Try to reconnect...","time":"2022-11-13T13:24:13.430Z","v":0}
```

What is the expected result? (期待される動作)
-------------------------------------------

- 設定の変更が、nchanを通じて複数のGrowiで同期される

解決方法
-------------------------------------------
Growi起動時のエラーにおいて
```
SyntaxError: The URL's protocol must be one of \"ws:\", \"wss:\", or \"ws+unix:\"
```
とある通り、`NCHAN_URI`のプロトコルはws:, wss:, または ws+unix:でないと動作しないと思われる
よって、冒頭で述べたとおり
```
NCHAN_URI=ws://nchan
```
とすることで解決できました

[GROWI Developers Wiki](https://dev.growi.org/5f0ee2c18c252f0048289de4)によると
GROWI は nchanから設定変更を `subscribe`する際、WebSocketを用いるようなので
URIのプロトコルは`ws://`である必要があると思われます
